module.exports = {
  parserOptions: {
    ecmaVersion: 5
  },
  rules: {
    'array-bracket-newline': [ 'error', { multiline: true }],
    'array-bracket-spacing': [ 'error', 'always', { arraysInArrays: false, objectsInArrays: false }],
    'array-callback-return': 'error',
    'array-element-newline': 'off',
    'accessor-pairs': 'off',
    'block-scoped-var': 'error',
    'block-spacing': [ 'error', 'always' ],
    'brace-style': [ 'error', '1tbs', { allowSingleLine: false }],
    'callback-return': 'off',
    'camelcase': [ 'error', { properties: 'never' }],
    'capitalized-comments': 'off',
    'comma-dangle': [ 'error', 'never' ],
    'comma-spacing': [ 'error', { before: false, after: true }],
    'comma-style': [ 'error', 'last' ],
    'complexity': [ 'error', 12 ],
    'computed-property-spacing': [ 'error', 'never' ],
    'consistent-return': 'error',
    'consistent-this': [ 'error', '_this' ],
    'constructor-super': 'off',
    'curly': [ 'error', 'all' ],
    'default-case': 'off',
    'dot-location': [ 'error', 'property' ],
    'dot-notation': [ 'error', { allowKeywords: true, allowPattern: '' }],
    'eol-last': 'error',
    'eqeqeq': 'error',
    'for-direction': 'error',
    'func-call-spacing': [ 'error', 'never' ],
    'func-name-matching': 'off',
    'func-names': [ 'error', 'never' ],
    'func-style': [ 'error', 'declaration', { allowArrowFunctions: true }],
    'function-paren-newline': [ 'error', 'consistent' ],
    'getter-return': 'error',
    'guard-for-in': 'error',
    'handle-callback-err': 'error',
    'id-blacklist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    'indent': [
      'error', 2, {
        outerIIFEBody: 1,
        SwitchCase: 0,
        VariableDeclarator: 1,
        MemberExpression: 'off',
        FunctionDeclaration: {
          parameters: 2,
          body: 1
        },
        FunctionExpression: {
          parameters: 2,
          body: 1
        },
        CallExpression: {
          arguments: 1
        },
        ArrayExpression: 1,
        ObjectExpression: 1,
        ImportDeclaration: 1,
        flatTernaryExpressions: false,
        ignoredNodes: [
          'JSXIdentifier',
          'JSXMemberExpression',
          'JSXNamespacedName',
          'JSXEmptyExpression',
          'JSXExpressionContainer',
          'JSXSpreadChild',
          'JSXBoundaryElement',
          'JSXOpeningElement',
          'JSXClosingElement',
          'JSXAttribute',
          'JSXSpreadAttribute',
          'JSXText',
          'JSXElement',
          'JSXFragment'
        ],
        ignoreComments: false
      }
    ],
    'init-declarations': 'off',
    'key-spacing': [ 'error', { beforeColon: false, afterColon: true, mode: 'strict' }],
    'keyword-spacing': [ 'error', { before: true, after: true }],
    'line-comment-position': 'off',
    'linebreak-style': [ 'error', 'unix' ],
    'lines-around-comment': [
      'error', {
        beforeBlockComment: true,
        beforeLineComment: true,
        afterBlockComment: false,
        afterLineComment: false,
        allowBlockStart: true,
        allowBlockEnd: false
      }
    ],
    'max-depth': 'off',
    'max-len': [ 'error', 120, 2, { ignoreComments: false, ignoreStrings: true, ignoreUrls: true, ignoreTemplateLiterals: true, ignoreRegExpLiterals: true }],
    'max-lines': 'off',
    'max-nested-callbacks': [ 'error', 7 ],
    'max-params': 'off',
    'max-statements': 'off',
    'max-statements-per-line': [ 'error', { max: 1 }],
    'multiline-comment-style': [ 'error', 'separate-lines' ],
    'multiline-ternary': 'off',
    'new-cap': [ 'error', { newIsCap: true, capIsNew: false, properties: false }],
    'new-parens': 'error',
    'newline-after-var': 'error',
    'newline-per-chained-call': 'off',
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-bitwise': 'off',
    'no-caller': 'error',
    'no-catch-shadow': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': [ 'error', 'always' ],
    'no-console': 'error',
    'no-const-assign': 'error',
    'no-constant-condition': 'error',
    'no-continue': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-div-regex': 'error',
    'no-dupe-args': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-else-return': 'error',
    'no-empty': [ 'error', { allowEmptyCatch: true }],
    'no-empty-function': [ 'error', { allow: [ 'arrowFunctions' ] }],
    'no-empty-character-class': 'error',
    'no-eq-null': 'off',
    'no-eval': 'error',
    'no-ex-assign': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-label': 'error',
    'no-extra-parens': [ 'error', 'all', { ignoreJSX: 'multi-line', nestedBinaryExpressions: false }],
    'no-extra-semi': 'error',
    'no-fallthrough': 'error',
    'no-floating-decimal': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-implicit-coercion': 'off',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-inline-comments': 'error',
    'no-inner-declarations': [ 'error', 'functions' ],
    'no-invalid-regexp': 'error',
    'no-invalid-this': 'error',
    'no-irregular-whitespace': 'error',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-magic-numbers': [ 'error', { ignore: [ 0, 1, -1 ], ignoreArrayIndexes: true }],
    'no-mixed-operators': 'error',
    'no-mixed-spaces-and-tabs': 'error',
    'no-multi-assign': 'error',
    'no-multi-spaces': 'error',
    'no-multi-str': 'error',
    'no-multiple-empty-lines': [ 'error', { max: 1, maxEOF: 1, maxBOF: 1 }],
    'no-native-reassign': 'error',
    'no-negated-condition': 'off',
    'no-negated-in-lhs': 'error',
    'no-nested-ternary': 'off',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-require': 'error',
    'no-new-wrappers': 'error',
    'no-obj-calls': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': [ 'error', { props: false }],
    'no-path-concat': 'error',
    'no-plusplus': 'off',
    'no-proto': 'error',
    'no-prototype-builtins': 'off',
    'no-redeclare': [ 'error', { builtinGlobals: true }],
    'no-regex-spaces': 'error',
    'no-restricted-globals': 'off',
    'no-restricted-syntax': 'off',
    'no-return-assign': [ 'error', 'always' ],
    'no-script-url': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow': 'off',
    'no-shadow-restricted-names': 'error',
    'no-spaced-func': 'error',
    'no-sparse-arrays': 'error',
    'no-tabs': 'error',
    'no-ternary': 'off',
    'no-trailing-spaces': 'error',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-undef': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'error',
    'no-unexpected-multiline': 'error',
    'no-underscore-dangle': 'off',
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'off',
    'no-unsafe-negation': 'error',
    'no-unused-expressions': 'off',
    'no-unused-labels': 'error',
    'no-unused-vars': [ 'error', { vars: 'all', args: 'after-used' }],
    'no-use-before-define': 'off',
    'no-useless-call': 'error',
    'no-useless-concat': 'error',
    'no-useless-escape': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-warning-comments': [ 'error', { terms: [ 'todo', 'fixme' ], location: 'start' }],
    'no-whitespace-before-property': 'error',
    'no-with': 'error',
    'nonblock-statement-body-position': 'off',
    'object-curly-newline': 'off',
    'object-curly-spacing': [ 'error', 'always', { arraysInObjects: true, objectsInObjects: true }],
    'object-property-newline': 'off',
    'one-var': [ 'error', { var: 'always' }],
    'one-var-declaration-per-line': [ 'error', 'initializations' ],
    'operator-assignment': 'off',
    'operator-linebreak': [ 'off', 'after', { overrides: { '?': 'before', ':': 'before' } }],
    'padded-blocks': [ 'error', 'never' ],
    'padding-line-between-statements': [
      'error',
      { blankLine: 'always', prev: '*', next: 'return' },
      { blankLine: 'always', prev: '*', next: 'try' },
      { blankLine: 'always', prev: '*', next: 'throw' },
      { blankLine: 'any', prev: 'block-like', next: 'throw' },
      { blankLine: 'always', prev: [ 'const', 'let', 'var' ], next: '*' },
      { blankLine: 'any', prev: [ 'const', 'let', 'var' ], next: [ 'const', 'let', 'var' ] },
      { blankLine: 'never', prev: '*', next: [ 'break', 'case', 'default' ] },
      { blankLine: 'always', prev: '*', next: 'cjs-export' },
      { blankLine: 'always', prev: 'cjs-import', next: '*' },
      { blankLine: 'any', prev: 'cjs-import', next: 'cjs-import' },
      { blankLine: 'always', prev: '*', next: 'class' },
      { blankLine: 'always', prev: 'directive', next: '*' },
      { blankLine: 'any', prev: 'directive', next: 'directive' },
      { blankLine: 'always', prev: '*', next: [ 'do', 'if', 'while', 'for', 'switch' ] },
      { blankLine: 'any', prev: [ 'do', 'if', 'while', 'for', 'switch' ], next: [ 'do', 'if', 'while', 'for', 'switch' ] },
      { blankLine: 'always', prev: [ 'do', 'if', 'while', 'for', 'switch' ], next: '*' },
      { blankLine: 'any', prev: [ 'do', 'if', 'while', 'for', 'switch' ], next: [ 'do', 'if', 'while', 'for', 'switch' ] },
      { blankLine: 'always', prev: 'import', next: '*' },
      { blankLine: 'any', prev: 'import', next: 'import' },
      { blankLine: 'always', prev: '*', next: 'export' },
      { blankLine: 'always', prev: '*', next: 'function' },
      { blankLine: 'any', prev: [ 'block', 'block-like' ], next: 'function' }
    ],
    'quote-props': [ 'error', 'consistent-as-needed' ],
    'quotes': [ 'error', 'single' ],
    'radix': ['error', 'as-needed'],
    'require-jsdoc': 'off',
    'semi': [ 'error', 'always' ],
    'semi-spacing': [ 'error', { before: false, after: true }],
    'semi-style': [ 'error', 'last' ],
    'sort-keys': 'off',
    'sort-vars': 'off',
    'space-before-blocks': [ 'error', 'always' ],
    'space-before-function-paren': [
      'error', {
        anonymous: 'never',
        named: 'never',
        asyncArrow: 'always'
      }
    ],
    'space-in-parens': [ 'error', 'never' ],
    'space-infix-ops': 'error',
    'space-unary-ops': [ 'error', { words: true, nonwords: false }],
    'spaced-comment': [ 'error', 'always' ],
    'switch-colon-spacing': [ 'error', { after: true, before: false }],
    'strict': [ 'error', 'never' ],
    'unicode-bom': [ 'error', 'never' ],
    'use-isnan': 'error',
    'valid-jsdoc': [
      'error', {
        prefer: {
          return: 'returns'
        },
        preferType: {
          array: 'Array',
          Boolean: 'boolean',
          Number: 'number',
          String: 'string'
        },
        requireParamDescription: true,
        requireReturn: false,
        requireReturnDescription: true
      }
    ],
    'valid-typeof': [ 'error', { requireStringLiterals: true }],
    'vars-on-top': 'error',
    'wrap-iife': [ 'error', 'outside' ],
    'wrap-regex': 'off',
    'yoda': [ 'error', 'never' ]
  }
};
