module.exports = {
  extends: [ 'eslint-config-adidas-es5' ].map(require.resolve),
  plugins: [
    'import',
    'promise'
  ],
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 6
  },
  env: {
    es6: true
  },
  rules: {
    'arrow-body-style': [ 'error', 'as-needed' ],
    'arrow-parens': [ 'error', 'always' ],
    'arrow-spacing': [ 'error', { before: true, after: true }],
    'class-methods-use-this': 'off',
    'constructor-super': 'error',
    'func-names': [ 'error', 'never', { generators: 'as-needed' }],
    'generator-star-spacing': [ 'error', 'after' ],
    'implicit-arrow-linebreak': 'off',
    'lines-between-class-members': 'off',
    'max-classes-per-file': 'off',
    'no-class-assign': 'error',
    'no-confusing-arrow': [ 'off', { allowParens: true }],
    'no-const-assign': 'error',
    'no-constructor-return': 'off',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': 'error',
    'no-empty-pattern': 'error',
    'no-import-assign': 'off',
    'no-iterator': 'error',
    'no-new-symbol': 'error',
    'no-restricted-exports': 'off',
    'no-restricted-imports': 'off',
    'no-restricted-modules': 'off',
    'no-template-curly-in-string': 'error',
    'no-this-before-super': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-var': 'error',
    'object-shorthand': [
      'error',
      'always',
      { avoidQuotes: true, avoidExplicitReturnArrows: true }
    ],
    'one-var': [ 'error', { initialized: 'never' }],
    'prefer-arrow-callback': [
      'error',
      { allowNamedFunctions: false, allowUnboundThis: false }
    ],
    'prefer-const': [ 'error', { destructuring: 'all' }],
    'prefer-destructuring': [
      'error',
      { array: true, object: true },
      { enforceForRenamedProperties: false }
    ],
    'prefer-exponentiation-operator': 'off',
    'prefer-numeric-literals': 'off',
    'prefer-promise-reject-errors': 'off',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'require-atomic-updates': 'error',
    'require-yield': 'error',
    'rest-spread-spacing': [ 'error', 'never' ],
    'sort-imports': 'off',
    'symbol-description': 'error',
    'template-curly-spacing': [ 'error', 'always' ],
    'template-tag-spacing': [ 'error', 'always' ],
    'yield-star-spacing': [ 'error', 'after' ],

    'promise/catch-or-return': 'error',
    'promise/no-return-wrap': 'error',
    'promise/param-names': 'error',
    'promise/always-return': 'off',
    'promise/no-native': 'off',
    'promise/no-nesting': 'off',
    'promise/no-promise-in-callback': 'error',
    'promise/no-callback-in-promise': 'off',
    'promise/avoid-new': 'off',
    'promise/no-new-statics': 'error',
    'promise/no-return-in-finally': 'error',
    'promise/valid-params': 'error',

    'import/no-unresolved': 'off',
    'import/named': 'error',
    'import/default': 'error',
    'import/namespace': 'error',
    'import/no-restricted-paths': 'off',
    'import/no-absolute-path': 'error',
    'import/no-dynamic-require': 'off',
    'import/no-internal-modules': 'off',
    'import/no-webpack-loader-syntax': 'off',
    'import/no-self-import': 'error',
    'import/no-cycle': 'error',
    'import/no-useless-path-segments': 'error',
    'import/no-relative-parent-imports': 'off',
    'import/export': 'error',
    'import/no-named-as-default': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-deprecated': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-mutable-exports': 'error',
    'import/unambiguous': 'off',
    'import/no-commonjs': 'off',
    'import/no-amd': 'error',
    'import/no-nodejs-modules': 'off',
    'import/first': 'error',
    'import/exports-last': 'off',
    'import/no-duplicates': 'error',
    'import/no-namespace': 'off',
    'import/extensions': 'off',
    'import/order': [
      'error', {
        'groups': [ 'builtin', 'external', 'internal', 'parent', 'sibling', 'index' ],
        'newlines-between': 'never'
      }
    ],
    'import/newline-after-import': [ 'error', { count: 1 }],
    'import/prefer-default-export': 'off',
    'import/max-dependencies': 'off',
    'import/no-unassigned-import': 'off',
    'import/no-named-default': 'off',
    'import/no-anonymous-default-export': 'off',
    'import/group-exports': 'off',
    'import/dynamic-import-chunkname': 'off'
  }
};
